version: '3'
services:
  websocket-1:
    build: ./back-end
    environment:
      - NAME=Webserver One
    ports:
      - "${API_PORT_1}:1337"
      - "${SOCKET_PORT_1}:1337"
    links:
      - redis
  websocket-2:
    build: ./back-end
    environment:
      - NAME=Webserver Two
    ports:
      - "${API_PORT_2}:1337"
      - "${SOCKET_PORT_2}:1337"
    links:
      - redis
  redis:
    image: redis
    ports:
      - "3100:6379"